### ISSUE TITLE
CORS error on some canvas instances

### ISSUE THREAD

**Issue by jeremy-clakron** [pikapower9080/canvas-quickmenu#1]
im not certain why this is happening, as it is on a instructure.com domain
![image](https://github.com/user-attachments/assets/707e7271-e05d-442c-9178-a2e53ca71601)
when on the main page it just gives an error about cross site or something like that
`Content-Security-Policy: The page’s settings blocked the loading of a resource (connect-src) at https://gist.githubusercontent.com/pikapower9080/4b60adb4a04a11e20134ae0b756d66c4/raw/index.js because it violates the following directive: “connect-src 'self'...`

if you could help me get this working it would be much appreciated becuase this looks really cool!

**Comment by bleov** [comment]
Hi, this seems to be a problem with your school's canvas security settings. I obviously don't have access to every school's canvas, so I can't troubleshoot. I have an idea for a potential solution, which I'll work on right now.

**Comment by bleov** [comment]
Just fixed this, update your userscript with the new `userscript.js` and it should work. You will probably get a popup asking you if you want to allow the script to make a cross origin request. Be sure to click "Always allow" to avoid getting it in the future!

**Comment by jeremy-clakron** [comment]
thank you, sir!

**Comment by jeremy-clakron** [comment]
can confirm it works, thank you so much
